### ISSUE TITLE
别忘了进度啊

### ISSUE THREAD

**Issue by Gizeta** [Five-African/Five-African.github.io#1]
做完的自觉打勾
- [x] 整体布局
- [x] 内容模板
- [x] 组员信息
  - [x] 空鱼
  - [x] Clect
  - [x] Tadelaide
  - [x] TedHan
  - [x] AtrisMio
- [x] README.md
- [x] Wiki

**Comment by Gizeta** [comment]
wiki有没有要新增的内容，如果没有我就默认完成了。

**Comment by AtarisMio** [comment]
不仔细写些什么的么？

**Comment by Gizeta** [comment]
如果是布局框架相关的，那就交给你了 @AtrisMio

**Comment by Gizeta** [comment]
delay

**Comment by Gizeta** [comment]
wiki就不补充了
全部finished
